#### general settings
name: refusion_splitting
use_tb_logger: true
model: denoising
distortion: splitting
gpu_ids: [0]

sde:
  max_sigma: 20
  T: 100
  schedule: cosine # linear, cosine
  eps: 0.005

degradation: # for some synthetic dataset that only have GTs
  # for denoising
  # sigma: 25
  noise_type: G # Gaussian noise: G

  # for super-resolution
  # scale: 4
  
#### datasets
datasets:
  train:
    optimizer: Lion # Adam, AdamW, Lion
    name: Train_Dataset
    mode: LQGT_splitting
    fpath: /group/jug/ashesh/data/microscopy/OptiMEM100x014.tif
    downscale_factor: 6

    use_shuffle: true
    n_workers: 4  # per GPU
    batch_size: 16
    GT_size: 128
    LR_size: 128
    # use_flip: true
    # use_rot: true
    color: null
    
    # splitting dataset specific 
    channel_1: 2
    channel_2: 3
    target_channel_idx: 1 # This can only be either 0 or 1. 
    ch1_weight: 0.5
    datasplit_type: train
    enable_rotation_aug: true
    enable_random_cropping: true
    clip_percentile: 0.995
    channelwise_quantile: false
    background_quantile: 0.
    clip_background_noise_to_zero: false
    skip_normalization_using_mean: false
    val_fraction: 0.1
    test_fraction: 0.1
    empty_patch_max_val_threshold: 0.0

  val:
    datasplit_type: val
    optimizer: Lion # Adam, AdamW, Lion
    name: Val_Dataset
    mode: LQGT_splitting
    fpath: /group/jug/ashesh/data/microscopy/OptiMEM100x014.tif
    downscale_factor: 6

    use_shuffle: false
    n_workers: 4  # per GPU
    batch_size: 16
    GT_size: 128
    LR_size: 128
    # use_flip: true
    # use_rot: true
    color: null
    
    # splitting dataset specific 
    channel_1: 2
    channel_2: 3
    target_channel_idx: 1 # This can only be either 0 or 1. 
    ch1_weight: 0.5
    enable_rotation_aug: false
    enable_random_cropping: false
    clip_percentile: 0.995
    channelwise_quantile: false
    background_quantile: 0.
    clip_background_noise_to_zero: false
    skip_normalization_using_mean: false
    val_fraction: 0.1
    test_fraction: 0.1
    empty_patch_max_val_threshold: 0.0

  # val:
  #   name: Val_Dataset
  #   mode: LQGT_splitting
  #   dataroot_GT: /home/ziwlu/datasets/ntire2023/shadow/val/GT
  #   dataroot_LQ: /home/ziwlu/datasets/ntire2023/shadow/val/LQ


#### network structures
network_G:
  which_model_G: ConditionalNAFNet
  setting:
    width: 64
    enc_blk_nums: [1, 1, 1, 28]
    middle_blk_num: 3
    dec_blk_nums: [1, 1, 1, 1]

#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  optimizer: Lion # Adam, AdamW, Lion
  lr_G: !!float 4e-5
  lr_scheme: TrueCosineAnnealingLR
  beta1: 0.9
  beta2: 0.99
  niter: 700000
  warmup_iter: -1  # no warm up
  lr_steps: [200000, 400000, 600000]
  lr_gamma: 0.5
  eta_min: !!float 1e-7

  # criterion
  is_weighted: False
  loss_type: l1
  weight: 1.0

  manual_seed: 0
  val_freq: !!float 500

#### logger
logger:
  print_freq: 100
  # save_checkpoint_freq: !!float 5e3
